name: "Build"
on:
    push:
        tags:
            - *
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: build

